general:
steps:
  mtaBuild:
    buildTarget: 'CF'
    
  cloudFoundryDeploy:
      deployTool: 'mtaDeployPlugin'
      deployType: 'standard'
      cloudFoundry:
        org: 'DBS Japan Shared_dev'
        space: 'demo'
        credentialsId: 'CF_CREDENTIALSID'